---
- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart keepalived
  service: name=keepalived state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart consul
  service: name=consul state=restarted
  
- name: restart consul-template
  service: name=consul-template state=restarted